"""
Transparency label generation.  [planning.md > Transparency Label Design]

Maps a verdict + confidence into the plain-language label a reader sees on the
platform. Three variants, matching the verbatim text in planning.md / README:

  - likely_ai     -> hedged, non-accusatory, names the appeal path
  - likely_human  -> reassuring, framed as an estimate
  - uncertain     -> refuses to guess; asserts NO numeric confidence

The AI and human variants interpolate the actual confidence for THIS submission;
the uncertain variant deliberately shows no percentage (planning.md: "no numeric
confidence is asserted").
"""


def generate_label(verdict, confidence):
    """Return {"variant": str, "text": str} for the given verdict + confidence."""
    pct = round(confidence * 100)

    if verdict == "likely_ai":
        return {
            "variant": "likely_ai",
            "text": (
                f"⚠️ **Likely AI-Generated.** Our automated analysis suggests this text "
                f"was probably produced with AI (estimated confidence: {pct}%). This is a "
                f"statistical signal, not a certainty, and not an accusation. If you wrote "
                f"this yourself, you can appeal this assessment."
            ),
        }

    if verdict == "likely_human":
        return {
            "variant": "likely_human",
            "text": (
                f"✓ **Likely Human-Written.** Our automated analysis found no strong signs "
                f"of AI generation (estimated confidence: {pct}%). This is an estimate, not "
                f"a guarantee of authorship."
            ),
        }

    # uncertain (default)
    return {
        "variant": "uncertain",
        "text": (
            "❓ **Inconclusive.** We couldn't determine with confidence whether this was "
            "written by a person or generated by AI. Rather than guess, we're telling you "
            "plainly: no attribution claim is being made here."
        ),
    }
