"""
Signal 1 - LLM classification (Groq).  [planning.md > Detection Signals > Signal 1]

Semantic / holistic detector. Asks llama-3.3-70b-versatile to estimate the
probability that a passage was AI-generated.

Output shape:
    {
        "llm_score": float in [0, 1],   # 1.0 = strongly AI-like, 0.0 = strongly human-like
        "rationale": str                # one-line explanation from the model
    }
"""

import os
import re
import json
from groq import Groq

MODEL = "llama-3.3-70b-versatile"

SYSTEM_PROMPT = (
    "You are an AI-text detection assistant for a creative writing platform. "
    "You assess whether a passage of text was written by a human or generated by an AI model. "
    "You are calibrated and cautious: falsely accusing a human writer is worse than missing "
    "AI text, so when the signals are weak or mixed you stay near the middle (around 50). "
    "Respond ONLY with a single JSON object and no other text. "
    'Both values MUST be valid JSON: "ai_probability" is a bare integer, and "rationale" '
    'MUST be wrapped in double quotes. Do not include line breaks inside the rationale string.'
)

# Instruction text shown before the user's text. Kept separate so we can use plain
# string concatenation (NOT str.format) -- the literal { } braces in the JSON
# example would otherwise be misread as format placeholders.
INSTRUCTIONS = (
    "Assess the following text. Return a JSON object with exactly two keys:\n"
    '  "ai_probability": an integer 0-100 (estimated percent chance the text is AI-generated),\n'
    '  "rationale": a single short sentence (in double quotes) giving the main reason.\n\n'
    "Example of a valid response:\n"
    '{"ai_probability": 30, "rationale": "The phrasing is idiosyncratic and varied."}\n\n'
    "Text:\n"
)


def _build_user_prompt(text):
    return INSTRUCTIONS + '"""\n' + text + '\n"""'


def _parse_response(raw):
    """Parse the model output into (ai_probability, rationale).

    Tries strict JSON first; if the model emits slightly malformed JSON
    (e.g. an unquoted rationale), falls back to regex-extracting the number.
    Raises RuntimeError only if no probability can be recovered at all.
    """
    # 1. Strict JSON (the happy path).
    try:
        data = json.loads(raw)
        return float(data["ai_probability"]), str(data.get("rationale", "")).strip()
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        pass

    # 2. Fallback: pull the ai_probability number out of the raw text.
    num_match = re.search(r'"?ai_probability"?\s*[:=]\s*(\d{1,3})', raw)
    if not num_match:
        num_match = re.search(r'\b(\d{1,3})\b', raw)  # last resort: first number
    if not num_match:
        raise RuntimeError(f"Could not extract ai_probability from LLM response: {raw!r}")

    ai_probability = float(num_match.group(1))

    # Best-effort rationale (quoted or unquoted); fine if it's missing.
    rat_match = re.search(r'"?rationale"?\s*[:=]\s*"?([^"\n}]+)', raw)
    rationale = rat_match.group(1).strip().rstrip(",").strip() if rat_match else ""

    return ai_probability, rationale


def get_llm_signal(text, client=None):
    """Return the LLM signal for `text` as {"llm_score": float, "rationale": str}.

    Raises RuntimeError if the API key is missing, or if no score can be recovered.
    A `client` can be injected for testing.
    """
    if client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise RuntimeError("GROQ_API_KEY is not set. Add it to your .env file.")
        client = Groq(api_key=api_key)

    completion = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": _build_user_prompt(text)},
        ],
        temperature=0.0,
    )

    raw = completion.choices[0].message.content or ""
    ai_probability, rationale = _parse_response(raw)

    # Normalize 0-100 -> 0-1, clamp defensively.
    llm_score = max(0.0, min(1.0, ai_probability / 100.0))
    return {"llm_score": llm_score, "rationale": rationale}
